"""init db

Revision ID: 6dc0a0eb6868
Revises: 6e051b0bd171
Create Date: 2023-12-28 15:08:29.633160

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6dc0a0eb6868'
down_revision = '6e051b0bd171'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'disabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否失效',
               existing_comment='是否是激活',
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'disabled',
               existing_type=mysql.TINYINT(display_width=1),
               comment='是否是激活',
               existing_comment='是否失效',
               existing_nullable=True)
    # ### end Alembic commands ###
