"""init db

Revision ID: 985d2b372b96
Revises: 8d6e032cc6d1
Create Date: 2023-12-28 15:34:50.722828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '985d2b372b96'
down_revision = '8d6e032cc6d1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('databases', sa.Column('db_name', sa.String(length=255), nullable=False, comment='需要扫描的数据库'))
    op.drop_column('databases', 'scan_db_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('databases', sa.Column('scan_db_name', mysql.VARCHAR(length=255), nullable=False, comment='需要扫描的数据库'))
    op.drop_column('databases', 'db_name')
    # ### end Alembic commands ###
