"""init sc

Revision ID: 9a06e555181d
Revises: 985d2b372b96
Create Date: 2023-12-30 17:17:22.204773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a06e555181d'
down_revision = '985d2b372b96'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scan_db_history',
    sa.Column('db_id', sa.String(length=255), nullable=True, comment='数据库ID'),
    sa.Column('db_name', sa.String(length=255), nullable=True, comment='数据库名称'),
    sa.Column('add_table', sa.String(length=255), nullable=True, comment='新增表'),
    sa.Column('up_table', sa.String(length=255), nullable=True, comment='更新表'),
    sa.Column('del_table', sa.String(length=255), nullable=True, comment='删除表'),
    sa.Column('other', sa.String(length=255), nullable=True, comment='其他'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_db_history_db_id'), 'scan_db_history', ['db_id'], unique=False)
    op.create_index(op.f('ix_scan_db_history_db_name'), 'scan_db_history', ['db_name'], unique=False)
    op.create_table('scan_table',
    sa.Column('db_id', sa.String(length=255), nullable=True, comment='数据库ID'),
    sa.Column('db_name', sa.String(length=255), nullable=True, comment='数据库名称'),
    sa.Column('table_name', sa.String(length=255), nullable=True, comment='表名称'),
    sa.Column('table_desc', sa.String(length=255), nullable=True, comment='表描述'),
    sa.Column('table_md5', sa.String(length=255), nullable=True, comment='表md5'),
    sa.Column('table_status', sa.BOOLEAN(), nullable=True, comment='表状态'),
    sa.Column('other', sa.String(length=255), nullable=True, comment='其他'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_table_db_id'), 'scan_table', ['db_id'], unique=False)
    op.create_index(op.f('ix_scan_table_db_name'), 'scan_table', ['db_name'], unique=False)
    op.create_index(op.f('ix_scan_table_table_name'), 'scan_table', ['table_name'], unique=False)
    op.create_table('scan_table_history',
    sa.Column('db_id', sa.String(length=255), nullable=True, comment='数据库ID'),
    sa.Column('db_name', sa.String(length=255), nullable=True, comment='数据库名称'),
    sa.Column('table_name', sa.String(length=255), nullable=True, comment='表名称'),
    sa.Column('add_table', sa.String(length=255), nullable=True, comment='新增字段'),
    sa.Column('up_table', sa.String(length=255), nullable=True, comment='更新字段'),
    sa.Column('del_table', sa.String(length=255), nullable=True, comment='删除字段'),
    sa.Column('other', sa.String(length=255), nullable=True, comment='其他'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='id'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), server_default=sa.text('now()'), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scan_table_history_db_id'), 'scan_table_history', ['db_id'], unique=False)
    op.create_index(op.f('ix_scan_table_history_db_name'), 'scan_table_history', ['db_name'], unique=False)
    op.create_index(op.f('ix_scan_table_history_table_name'), 'scan_table_history', ['table_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scan_table_history_table_name'), table_name='scan_table_history')
    op.drop_index(op.f('ix_scan_table_history_db_name'), table_name='scan_table_history')
    op.drop_index(op.f('ix_scan_table_history_db_id'), table_name='scan_table_history')
    op.drop_table('scan_table_history')
    op.drop_index(op.f('ix_scan_table_table_name'), table_name='scan_table')
    op.drop_index(op.f('ix_scan_table_db_name'), table_name='scan_table')
    op.drop_index(op.f('ix_scan_table_db_id'), table_name='scan_table')
    op.drop_table('scan_table')
    op.drop_index(op.f('ix_scan_db_history_db_name'), table_name='scan_db_history')
    op.drop_index(op.f('ix_scan_db_history_db_id'), table_name='scan_db_history')
    op.drop_table('scan_db_history')
    # ### end Alembic commands ###
